version: '3.8'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql-db-flask
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: priv_web_db
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - web-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  invstore:
    build:
      context: .
      dockerfile: Dockerfile  # Specify your Dockerfile here
    image: bsimmons12/invstore
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"  # Adjust port as needed
    environment:
      - PORT=5000  # Set the port for NGINX to use
      - DATABASE_URL=mysql+mysqlconnector://root:password@mysql-db-flask:3306/invstore  # Use the assigned value
      - SECRET_KEY=unique_key  # Use the assigned value
    networks:
      - web-network
networks:
  web-network: